// "use client";

import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/_components/Navbar";
import { Box } from "@mui/material";
export const metadata: Metadata = {
  title: "Dr Syed Qasim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Box
          sx={{
            position: { xs: "fixed", sm: "unset" },
            top: "0",
            zIndex: "10000",
            width: "100%",
          }}
        >
          <Navbar />
        </Box>
        <Box sx={{ marginTop: { xs: "89px", sm: "unset" } }}>{children}</Box>
      </body>
      <ToastContainer position="top-right" autoClose={3000} />
    </html>
  );
}
