// // "use client";

// import type { Metadata } from "next";
// import "./globals.css";
// import { ToastContainer } from "react-toastify";
// import Navbar from "@/_components/Navbar";
// import { Box } from "@mui/material";
// export const metadata: Metadata = {
//   title: "Dr Syed Qasim",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <Box
//           sx={{
//             position: "fixed",
//             top: "0",
//             zIndex: "10000",
//             width: "100%",
//           }}
//         >
//           <Navbar />
//         </Box>
//         <Box sx={{ marginTop: { xs: "88.5px", md: "136px" } }}>{children}</Box>
//       </body>
//       <ToastContainer position="top-right" autoClose={3000} />
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NavbarWrapper from "@/_components/NavbarWrapper";
import LayoutSpacer from "@/_components/LayoutSpacer";

export const metadata: Metadata = {
  title: "Dr Syed Qasim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavbarWrapper />

        <LayoutSpacer>{children}</LayoutSpacer>

        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
